pull_request_rules:
  - name: Backport to release branch
    conditions:
      # Only apply this rule to pull requests merged into the develop branch
      - base=develop
      - merged
    actions:
      # Create a new pull request targeting the release branch
      backport:
        branches:
          - release
