version: "3.5"

services:
  simserver:
    container_name: sequencer
    image: lagrange-node
    networks:
      localnet:
        ipv4_address: 192.168.20.6
    ports:
      - 9090:9090
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-server"
  simnode0:
    container_name: node0
    image: lagrange-node
    environment:
      - LAGRANGE_NODE_CLIENT_GRPCURL=192.168.20.6:9090
      - LAGRANGE_NODE_CLIENT_PULLINTERVAL=2.4s
      - LAGRANGE_NODE_CLIENT_PRIVATEKEY=0x0642cf177a12c962938366d7c2d286f49806625831aaed8e861405bfdd1f654a
      - LAGRANGE_NODE_CLIENT_STAKEADDRESS=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
    networks:
      localnet:
        ipv4_address: 192.168.20.2
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-client"
  simnode1:
    container_name: node1
    image: lagrange-node
    environment:
      - LAGRANGE_NODE_CLIENT_GRPCURL=192.168.20.6:9090
      - LAGRANGE_NODE_CLIENT_PULLINTERVAL=2s
      - LAGRANGE_NODE_CLIENT_PRIVATEKEY=0xca056e1830045cd5aa844e02e493e27b8c454b3059315b8ee34d42414141247d
      - LAGRANGE_NODE_CLIENT_STAKEADDRESS=0x00000000219ab540356cbb839cbe05303d7705fa
    networks:
      localnet:
        ipv4_address: 192.168.20.3
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-client"
  simnode2:
    container_name: node2
    image: lagrange-node
    environment:
      - LAGRANGE_NODE_CLIENT_GRPCURL=192.168.20.6:9090
      - LAGRANGE_NODE_CLIENT_PULLINTERVAL=1.8s
      - LAGRANGE_NODE_CLIENT_PRIVATEKEY=0xa339d4976df7cc511ad3d31fb28407e0b92a3f876cc8d81434abfe27e09c0275
      - LAGRANGE_NODE_CLIENT_STAKEADDRESS=0xbe0eb53f46cd790cd13851d5eff43d12404d33e8
    networks:
      localnet:
        ipv4_address: 192.168.20.4
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-client"
  simnode3:
    container_name: node3
    image: lagrange-node
    environment:
      - LAGRANGE_NODE_CLIENT_GRPCURL=192.168.20.6:9090
      - LAGRANGE_NODE_CLIENT_PULLINTERVAL=2.2s
      - LAGRANGE_NODE_CLIENT_PRIVATEKEY=0x1002490094172864114bb1fa239db4d25399af2c2629368027d97e47b9ffaaa7
      - LAGRANGE_NODE_CLIENT_STAKEADDRESS=0xda9dfa130df4de4673b89022ee50ff26f6ea73cf
    networks:
      localnet:
        ipv4_address: 192.168.20.5
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-client"
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
   
networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/25
