version: "3.5"

services:
  simsequencer:
    container_name: sequencer
    image: lagrange-node
    networks:
      localnet:
        ipv4_address: 192.168.20.5
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-sequencer"
    environment:
      - LAGRANGE_NODE_SEQUENCER_RPCURL=http://192.168.20.100:8545
      - LAGRANGE_NODE_STORE_DBPATH=mongodb://192.168.20.101:27017
      - LAGRANGE_NODE_GOVERNANCE_ETHEREUMURL=http://192.168.20.100:8545
  simserver:
    container_name: server
    image: lagrange-node
    networks:
      localnet:
        ipv4_address: 192.168.20.6
    ports:
      - 9090:9090
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-server"
    environment:
      - LAGRANGE_NODE_SEQUENCER_RPCURL=http://192.168.20.100:8545
      - LAGRANGE_NODE_STORE_DBPATH=mongodb://192.168.20.101:27017
  simnode0:
    container_name: node0
    image: lagrange-node
    environment:
      - LAGRANGE_NODE_CLIENT_GRPCURL=192.168.20.6:9090
      - LAGRANGE_NODE_CLIENT_PULLINTERVAL=2.4s
      - LAGRANGE_NODE_CLIENT_BLSPRIVATEKEY=0x0642cf177a12c962938366d7c2d286f49806625831aaed8e861405bfdd1f654a
      - LAGRANGE_NODE_CLIENT_ECDSAPRIVATEKEY=0x232d99bc62cf95c358fb496e9f820ec299f43417397cea32f9f365daf4748429
      - LAGRANGE_NODE_CLIENT_RPCENDPOINT=http://192.168.20.100:8545
      - LAGRANGE_NODE_STORE_DBPATH=mongodb://192.168.20.101:27017
    networks:
      localnet:
        ipv4_address: 192.168.20.2
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-client"
  simnode1:
    container_name: node1
    image: lagrange-node
    environment:
      - LAGRANGE_NODE_CLIENT_GRPCURL=192.168.20.6:9090
      - LAGRANGE_NODE_CLIENT_PULLINTERVAL=2s
      - LAGRANGE_NODE_CLIENT_BLSPRIVATEKEY=0x475e7dc95f40ba8e5af29adb745ae3ac5d3404575b0f853c73ed1efa46943fc2
      - LAGRANGE_NODE_CLIENT_ECDSAPRIVATEKEY=0x25f536330df3a72fa381bfb5ea5552b2731523f08580e7a0e2e69618a9643faa
      - LAGRANGE_NODE_CLIENT_RPCENDPOINT=http://192.168.20.100:8545
      - LAGRANGE_NODE_STORE_DBPATH=mongodb://192.168.20.101:27017
    networks:
      localnet:
        ipv4_address: 192.168.20.3
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-client"
  simnode2:
    container_name: node2
    image: lagrange-node
    environment:
      - LAGRANGE_NODE_CLIENT_GRPCURL=192.168.20.6:9090
      - LAGRANGE_NODE_CLIENT_PULLINTERVAL=1.8s
      - LAGRANGE_NODE_CLIENT_BLSPRIVATEKEY=0x59ec5a675fa5a9805d791c58c97a3dcc0bc8def2029bd53aa33dc035f2b81404
      - LAGRANGE_NODE_CLIENT_ECDSAPRIVATEKEY=0xc262364335471942e02e79d760d1f5c5ad7a34463303851cacdd15d72e68b228
      - LAGRANGE_NODE_CLIENT_RPCENDPOINT=http://192.168.20.100:8545
      - LAGRANGE_NODE_STORE_DBPATH=mongodb://192.168.20.101:27017
    networks:
      localnet:
        ipv4_address: 192.168.20.4
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-client"
  lagrangesc:
    container_name: lagrange-smart-contract
    image: lagrangelabs/lagrange-contracts:latest
    networks:
      localnet:
        ipv4_address: 192.168.20.100
    ports:
      - "8545:8545"
  mongo:
    image: mongo:4.4
    container_name: mongo
    networks:
      localnet:
        ipv4_address: 192.168.20.101
    ports:
      - "27017:27017"

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/25
