name: Auto Tag and Push Docker Release Image

on:
  pull_request:
    types: [closed]
    branches:
      - release/v*

jobs:
  auto-tag-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Identify and Create New Tag
        id: new_tag
        run: |
          # Fetch tags and identify the latest
          git fetch --tags
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $LATEST_TAG"

          # Logic to increment the tag. This is a simple example; adjust as needed.
          NEW_TAG=$(echo $LATEST_TAG | awk -F. '{print $1"."$2"."$3+1}')
          echo "New tag: $NEW_TAG"

          # Create new tag and push
          git tag $NEW_TAG
          git push origin $NEW_TAG
          echo "::set-output name=tag::$NEW_TAG"

      - name: Get Commit Message
        id: get_commit
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          echo "::set-output name=message::$COMMIT_MESSAGE"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          tag_name: ${{ steps.new_tag.outputs.tag }}
          release_name: ${{ steps.get_commit.outputs.message }}
          draft: false
          prerelease: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            lagrangelabs/lagrange-node::${{ steps.new_tag.outputs.tag }}
